version: '3'

services:
  web:
    build: ./deus_api
    command: python manage.py runserver 0.0.0.0:8000  
    volumes:
      - - ./deus_api/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
     volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  volumes:
  postgres_data: