# Generated by Django 5.0.6 on 2024-05-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
