# Use an official Python runtime as a parent image
FROM python:3.10

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file into the container at /app
RUN pip install --upgrade pip
COPY ./requirements.txt .
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

COPY . .

# Expose port 8000 to the outside world
EXPOSE 8000

# Command to run the application
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]